// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenRequest) Reset()         { *m = GenerateTokenRequest{} }
func (m *GenerateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenRequest) ProtoMessage()    {}
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *GenerateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenRequest.Unmarshal(m, b)
}
func (m *GenerateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenRequest.Marshal(b, m, deterministic)
}
func (m *GenerateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenRequest.Merge(m, src)
}
func (m *GenerateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenRequest.Size(m)
}
func (m *GenerateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenRequest proto.InternalMessageInfo

func (m *GenerateTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GenerateTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenResponse) Reset()         { *m = GenerateTokenResponse{} }
func (m *GenerateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenResponse) ProtoMessage()    {}
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *GenerateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenResponse.Unmarshal(m, b)
}
func (m *GenerateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenResponse.Marshal(b, m, deterministic)
}
func (m *GenerateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenResponse.Merge(m, src)
}
func (m *GenerateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenResponse.Size(m)
}
func (m *GenerateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenResponse proto.InternalMessageInfo

func (m *GenerateTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenValidityRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenValidityRequest) Reset()         { *m = TokenValidityRequest{} }
func (m *TokenValidityRequest) String() string { return proto.CompactTextString(m) }
func (*TokenValidityRequest) ProtoMessage()    {}
func (*TokenValidityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *TokenValidityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValidityRequest.Unmarshal(m, b)
}
func (m *TokenValidityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValidityRequest.Marshal(b, m, deterministic)
}
func (m *TokenValidityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValidityRequest.Merge(m, src)
}
func (m *TokenValidityRequest) XXX_Size() int {
	return xxx_messageInfo_TokenValidityRequest.Size(m)
}
func (m *TokenValidityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValidityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValidityRequest proto.InternalMessageInfo

func (m *TokenValidityRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenValidityRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenValidityResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenValidityResponse) Reset()         { *m = TokenValidityResponse{} }
func (m *TokenValidityResponse) String() string { return proto.CompactTextString(m) }
func (*TokenValidityResponse) ProtoMessage()    {}
func (*TokenValidityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *TokenValidityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValidityResponse.Unmarshal(m, b)
}
func (m *TokenValidityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValidityResponse.Marshal(b, m, deterministic)
}
func (m *TokenValidityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValidityResponse.Merge(m, src)
}
func (m *TokenValidityResponse) XXX_Size() int {
	return xxx_messageInfo_TokenValidityResponse.Size(m)
}
func (m *TokenValidityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValidityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValidityResponse proto.InternalMessageInfo

func (m *TokenValidityResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type LogoutRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenerateTokenRequest)(nil), "proto.GenerateTokenRequest")
	proto.RegisterType((*GenerateTokenResponse)(nil), "proto.GenerateTokenResponse")
	proto.RegisterType((*TokenValidityRequest)(nil), "proto.TokenValidityRequest")
	proto.RegisterType((*TokenValidityResponse)(nil), "proto.TokenValidityResponse")
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "proto.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "proto.LogoutResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x69, 0xa0, 0xa5, 0x8e, 0x5a, 0x64, 0x9b, 0x80, 0xc4, 0xa2, 0x92, 0x8b, 0x82, 0xb4,
	0x85, 0x8a, 0x0f, 0x50, 0x05, 0xf5, 0xe0, 0x41, 0xa2, 0x78, 0xf0, 0x16, 0xb7, 0x83, 0x89, 0x31,
	0x99, 0xb8, 0xbb, 0x51, 0x7c, 0x19, 0x9f, 0x55, 0xb2, 0xd9, 0xa6, 0x31, 0x44, 0xc8, 0x29, 0x99,
	0x99, 0x7f, 0xbe, 0xc9, 0xfc, 0x13, 0x80, 0x20, 0x57, 0xe1, 0x2c, 0x13, 0xa4, 0x88, 0xf5, 0xf5,
	0xc3, 0x5b, 0x80, 0x7d, 0x83, 0x29, 0x8a, 0x40, 0xe1, 0x23, 0xc5, 0x98, 0xfa, 0xf8, 0x91, 0xa3,
	0x54, 0xcc, 0x85, 0x61, 0x2e, 0x51, 0xa4, 0x41, 0x82, 0xfb, 0xbd, 0xe3, 0xde, 0xe9, 0x96, 0x5f,
	0xc5, 0xde, 0x14, 0x9c, 0x46, 0x8f, 0xcc, 0x28, 0x95, 0xc8, 0x6c, 0xe8, 0xab, 0x22, 0x61, 0x3a,
	0xca, 0xc0, 0xbb, 0x05, 0x5b, 0xcb, 0x9e, 0x82, 0xf7, 0x68, 0x15, 0xa9, 0xef, 0x0e, 0x23, 0x36,
	0x24, 0xab, 0x4e, 0x3a, 0x01, 0xa7, 0x41, 0x32, 0x83, 0x47, 0x60, 0x51, 0xac, 0x21, 0x43, 0xdf,
	0xa2, 0xd8, 0xbb, 0x86, 0x9d, 0x3b, 0x7a, 0x8d, 0xba, 0x6c, 0x53, 0xd4, 0xb2, 0x40, 0xca, 0x2f,
	0x12, 0x2b, 0x33, 0xad, 0x8a, 0xbd, 0x23, 0xd8, 0x35, 0x9c, 0x7f, 0x06, 0x9d, 0x69, 0x01, 0xe5,
	0xaa, 0x8b, 0x6f, 0x7b, 0x30, 0x5a, 0x8b, 0x4b, 0xdc, 0xe2, 0xc7, 0x82, 0xed, 0x65, 0xae, 0xc2,
	0x07, 0x14, 0x9f, 0x11, 0x47, 0x76, 0x0f, 0xe3, 0xb5, 0xb3, 0x4b, 0xce, 0x51, 0x4a, 0xbd, 0x2e,
	0x3b, 0x28, 0x6f, 0x36, 0x6b, 0xbb, 0x94, 0x3b, 0x69, 0x2f, 0x9a, 0x0f, 0xf6, 0xc1, 0xb9, 0x0a,
	0x91, 0xc7, 0x35, 0x9c, 0x76, 0xaf, 0x62, 0xb6, 0x9d, 0xa6, 0x62, 0xb6, 0xbb, 0xbd, 0x80, 0xbe,
	0x76, 0x85, 0x8d, 0x8d, 0xac, 0xee, 0xb5, 0x6b, 0xff, 0x4d, 0x9a, 0x9e, 0x0b, 0x18, 0x94, 0xbb,
	0xb3, 0x5a, 0x7d, 0xe3, 0x9b, 0xeb, 0x34, 0xb2, 0x65, 0xdb, 0xe5, 0xe1, 0xf3, 0x64, 0x25, 0xa7,
	0x99, 0xa0, 0x37, 0xe4, 0x6a, 0xce, 0x29, 0x49, 0x28, 0x9d, 0x6b, 0xe5, 0xbc, 0xf8, 0x97, 0x5f,
	0x06, 0xfa, 0xfd, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x8f, 0x6d, 0x39, 0xda, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	GenerateAccessToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	CheckAccessTokenValid(ctx context.Context, in *TokenValidityRequest, opts ...grpc.CallOption) (*TokenValidityResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GenerateAccessToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/GenerateAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckAccessTokenValid(ctx context.Context, in *TokenValidityRequest, opts ...grpc.CallOption) (*TokenValidityResponse, error) {
	out := new(TokenValidityResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/CheckAccessTokenValid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	GenerateAccessToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	CheckAccessTokenValid(context.Context, *TokenValidityRequest) (*TokenValidityResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) GenerateAccessToken(ctx context.Context, req *GenerateTokenRequest) (*GenerateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessToken not implemented")
}
func (*UnimplementedAuthServiceServer) CheckAccessTokenValid(ctx context.Context, req *TokenValidityRequest) (*TokenValidityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccessTokenValid not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GenerateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/GenerateAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateAccessToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckAccessTokenValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckAccessTokenValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/CheckAccessTokenValid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckAccessTokenValid(ctx, req.(*TokenValidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAccessToken",
			Handler:    _AuthService_GenerateAccessToken_Handler,
		},
		{
			MethodName: "CheckAccessTokenValid",
			Handler:    _AuthService_CheckAccessTokenValid_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
