//// Code generated by protoc-gen-go. DO NOT EDIT.
//// versions:
//// 	protoc-gen-go v1.20.1
//// 	protoc        v3.11.4
//// source: common/proto/users.proto
//
//package userproto
//
//import (
//	context "context"
//	proto "github.com/golang/protobuf/proto"
//	grpc "google.golang.org/grpc"
//	codes "google.golang.org/grpc/codes"
//	status "google.golang.org/grpc/status"
//	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
//	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
//	reflect "reflect"
//	sync "sync"
//)
//
//const (
//	// Verify that this generated code is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
//	// Verify that runtime/protoimpl is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
//)
//
//// This is a compile-time assertion that a sufficiently up-to-date version
//// of the legacy proto package is being used.
//const _ = proto.ProtoPackageIsVersion4
//
//type TOKEN struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
//}
//
//func (x *TOKEN) Reset() {
//	*x = TOKEN{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[0]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *TOKEN) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*TOKEN) ProtoMessage() {}
//
//func (x *TOKEN) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[0]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use TOKEN.ProtoReflect.Descriptor instead.
//func (*TOKEN) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{0}
//}
//
//func (x *TOKEN) GetToken() string {
//	if x != nil {
//		return x.Token
//	}
//	return ""
//}
//
//type USERNAME struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
//}
//
//func (x *USERNAME) Reset() {
//	*x = USERNAME{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[1]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *USERNAME) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*USERNAME) ProtoMessage() {}
//
//func (x *USERNAME) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[1]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use USERNAME.ProtoReflect.Descriptor instead.
//func (*USERNAME) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{1}
//}
//
//func (x *USERNAME) GetUsername() string {
//	if x != nil {
//		return x.Username
//	}
//	return ""
//}
//
//type VALID struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	IsValid bool `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
//}
//
//func (x *VALID) Reset() {
//	*x = VALID{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[2]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *VALID) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*VALID) ProtoMessage() {}
//
//func (x *VALID) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[2]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use VALID.ProtoReflect.Descriptor instead.
//func (*VALID) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{2}
//}
//
//func (x *VALID) GetIsValid() bool {
//	if x != nil {
//		return x.IsValid
//	}
//	return false
//}
//
//type REGISTER struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
//	Fullname string `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
//	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
//}
//
//func (x *REGISTER) Reset() {
//	*x = REGISTER{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[3]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *REGISTER) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*REGISTER) ProtoMessage() {}
//
//func (x *REGISTER) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[3]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use REGISTER.ProtoReflect.Descriptor instead.
//func (*REGISTER) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{3}
//}
//
//func (x *REGISTER) GetUsername() string {
//	if x != nil {
//		return x.Username
//	}
//	return ""
//}
//
//func (x *REGISTER) GetFullname() string {
//	if x != nil {
//		return x.Fullname
//	}
//	return ""
//}
//
//func (x *REGISTER) GetPassword() string {
//	if x != nil {
//		return x.Password
//	}
//	return ""
//}
//
//type LOGIN struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
//	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
//}
//
//func (x *LOGIN) Reset() {
//	*x = LOGIN{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[4]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *LOGIN) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*LOGIN) ProtoMessage() {}
//
//func (x *LOGIN) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[4]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use LOGIN.ProtoReflect.Descriptor instead.
//func (*LOGIN) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{4}
//}
//
//func (x *LOGIN) GetUsername() string {
//	if x != nil {
//		return x.Username
//	}
//	return ""
//}
//
//func (x *LOGIN) GetPassword() string {
//	if x != nil {
//		return x.Password
//	}
//	return ""
//}
//
//type USER struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
//	Fullname string `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
//}
//
//func (x *USER) Reset() {
//	*x = USER{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[5]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *USER) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*USER) ProtoMessage() {}
//
//func (x *USER) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[5]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use USER.ProtoReflect.Descriptor instead.
//func (*USER) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{5}
//}
//
//func (x *USER) GetUsername() string {
//	if x != nil {
//		return x.Username
//	}
//	return ""
//}
//
//func (x *USER) GetFullname() string {
//	if x != nil {
//		return x.Fullname
//	}
//	return ""
//}
//
//type USERS struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Users []*USER `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
//}
//
//func (x *USERS) Reset() {
//	*x = USERS{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[6]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *USERS) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*USERS) ProtoMessage() {}
//
//func (x *USERS) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[6]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use USERS.ProtoReflect.Descriptor instead.
//func (*USERS) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{6}
//}
//
//func (x *USERS) GetUsers() []*USER {
//	if x != nil {
//		return x.Users
//	}
//	return nil
//}
//
//type CHECKACCESSTOKEN struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
//	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
//}
//
//func (x *CHECKACCESSTOKEN) Reset() {
//	*x = CHECKACCESSTOKEN{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[7]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *CHECKACCESSTOKEN) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*CHECKACCESSTOKEN) ProtoMessage() {}
//
//func (x *CHECKACCESSTOKEN) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[7]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use CHECKACCESSTOKEN.ProtoReflect.Descriptor instead.
//func (*CHECKACCESSTOKEN) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{7}
//}
//
//func (x *CHECKACCESSTOKEN) GetUsername() string {
//	if x != nil {
//		return x.Username
//	}
//	return ""
//}
//
//func (x *CHECKACCESSTOKEN) GetToken() string {
//	if x != nil {
//		return x.Token
//	}
//	return ""
//}
//
//type REQ struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Nothing string `protobuf:"bytes,1,opt,name=nothing,proto3" json:"nothing,omitempty"`
//}
//
//func (x *REQ) Reset() {
//	*x = REQ{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_common_proto_users_proto_msgTypes[8]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *REQ) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*REQ) ProtoMessage() {}
//
//func (x *REQ) ProtoReflect() protoreflect.Message {
//	mi := &file_common_proto_users_proto_msgTypes[8]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use REQ.ProtoReflect.Descriptor instead.
//func (*REQ) Descriptor() ([]byte, []int) {
//	return file_common_proto_users_proto_rawDescGZIP(), []int{8}
//}
//
//func (x *REQ) GetNothing() string {
//	if x != nil {
//		return x.Nothing
//	}
//	return ""
//}
//
//var File_common_proto_users_proto protoreflect.FileDescriptor
//
//var file_common_proto_users_proto_rawDesc = []byte{
//	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75,
//	0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x75, 0x73, 0x65, 0x72,
//	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x12, 0x14,
//	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
//	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x26, 0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x4e, 0x41, 0x4d, 0x45,
//	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
//	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x05,
//	0x56, 0x41, 0x4c, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64,
//	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x22,
//	0x5e, 0x0a, 0x08, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x12, 0x1a, 0x0a, 0x08, 0x75,
//	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
//	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e,
//	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e,
//	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
//	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
//	0x3f, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
//	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
//	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
//	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
//	0x22, 0x3e, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
//	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
//	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
//	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
//	0x22, 0x2e, 0x0a, 0x05, 0x55, 0x53, 0x45, 0x52, 0x53, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x65,
//	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70,
//	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x53, 0x45, 0x52, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
//	0x22, 0x44, 0x0a, 0x10, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x54,
//	0x4f, 0x4b, 0x45, 0x4e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
//	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
//	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
//	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1f, 0x0a, 0x03, 0x52, 0x45, 0x51, 0x12, 0x18, 0x0a,
//	0x07, 0x6e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
//	0x6e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x32, 0xdf, 0x02, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
//	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73,
//	0x74, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
//	0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x1a, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70,
//	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x53, 0x45, 0x52, 0x12, 0x2c, 0x0a, 0x06, 0x53, 0x69, 0x67,
//	0x6e, 0x49, 0x6e, 0x12, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
//	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
//	0x6f, 0x2e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73,
//	0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
//	0x52, 0x45, 0x51, 0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
//	0x55, 0x53, 0x45, 0x52, 0x53, 0x12, 0x3c, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73,
//	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x13, 0x2e, 0x75,
//	0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x53, 0x45, 0x52, 0x4e, 0x41, 0x4d,
//	0x45, 0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x41,
//	0x4c, 0x49, 0x44, 0x12, 0x3c, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41,
//	0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65,
//	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x53, 0x45, 0x52, 0x4e, 0x41, 0x4d, 0x45, 0x1a,
//	0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4f, 0x4b, 0x45,
//	0x4e, 0x12, 0x46, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
//	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65,
//	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x41, 0x43, 0x43, 0x45,
//	0x53, 0x53, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x1a, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72,
//	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
//	0x33,
//}
//
//var (
//	file_common_proto_users_proto_rawDescOnce sync.Once
//	file_common_proto_users_proto_rawDescData = file_common_proto_users_proto_rawDesc
//)
//
//func file_common_proto_users_proto_rawDescGZIP() []byte {
//	file_common_proto_users_proto_rawDescOnce.Do(func() {
//		file_common_proto_users_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_users_proto_rawDescData)
//	})
//	return file_common_proto_users_proto_rawDescData
//}
//
//var file_common_proto_users_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
//var file_common_proto_users_proto_goTypes = []interface{}{
//	(*TOKEN)(nil),            // 0: userproto.TOKEN
//	(*USERNAME)(nil),         // 1: userproto.USERNAME
//	(*VALID)(nil),            // 2: userproto.VALID
//	(*REGISTER)(nil),         // 3: userproto.REGISTER
//	(*LOGIN)(nil),            // 4: userproto.LOGIN
//	(*USER)(nil),             // 5: userproto.USER
//	(*USERS)(nil),            // 6: userproto.USERS
//	(*CHECKACCESSTOKEN)(nil), // 7: userproto.CHECKACCESSTOKEN
//	(*REQ)(nil),              // 8: userproto.REQ
//}
//var file_common_proto_users_proto_depIdxs = []int32{
//	5, // 0: userproto.USERS.users:type_name -> userproto.USER
//	3, // 1: userproto.UserService.Register:input_type -> userproto.REGISTER
//	4, // 2: userproto.UserService.SignIn:input_type -> userproto.LOGIN
//	8, // 3: userproto.UserService.GetUsers:input_type -> userproto.REQ
//	1, // 4: userproto.UserService.CheckUserNameExists:input_type -> userproto.USERNAME
//	1, // 5: userproto.UserService.GenerateAccessToken:input_type -> userproto.USERNAME
//	7, // 6: userproto.UserService.CheckAccessTokenValid:input_type -> userproto.CHECKACCESSTOKEN
//	5, // 7: userproto.UserService.Register:output_type -> userproto.USER
//	2, // 8: userproto.UserService.SignIn:output_type -> userproto.VALID
//	6, // 9: userproto.UserService.GetUsers:output_type -> userproto.USERS
//	2, // 10: userproto.UserService.CheckUserNameExists:output_type -> userproto.VALID
//	0, // 11: userproto.UserService.GenerateAccessToken:output_type -> userproto.TOKEN
//	2, // 12: userproto.UserService.CheckAccessTokenValid:output_type -> userproto.VALID
//	7, // [7:13] is the sub-list for method output_type
//	1, // [1:7] is the sub-list for method input_type
//	1, // [1:1] is the sub-list for extension type_name
//	1, // [1:1] is the sub-list for extension extendee
//	0, // [0:1] is the sub-list for field type_name
//}
//
//func init() { file_common_proto_users_proto_init() }
//func file_common_proto_users_proto_init() {
//	if File_common_proto_users_proto != nil {
//		return
//	}
//	if !protoimpl.UnsafeEnabled {
//		file_common_proto_users_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*TOKEN); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*USERNAME); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*VALID); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*REGISTER); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*LOGIN); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*USER); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*USERS); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*CHECKACCESSTOKEN); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_common_proto_users_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*REQ); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//	}
//	type x struct{}
//	out := protoimpl.TypeBuilder{
//		File: protoimpl.DescBuilder{
//			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
//			RawDescriptor: file_common_proto_users_proto_rawDesc,
//			NumEnums:      0,
//			NumMessages:   9,
//			NumExtensions: 0,
//			NumServices:   1,
//		},
//		GoTypes:           file_common_proto_users_proto_goTypes,
//		DependencyIndexes: file_common_proto_users_proto_depIdxs,
//		MessageInfos:      file_common_proto_users_proto_msgTypes,
//	}.Build()
//	File_common_proto_users_proto = out.File
//	file_common_proto_users_proto_rawDesc = nil
//	file_common_proto_users_proto_goTypes = nil
//	file_common_proto_users_proto_depIdxs = nil
//}
//
//// Reference imports to suppress errors if they are not otherwise used.
//var _ context.Context
//var _ grpc.ClientConnInterface
//
//// This is a compile-time assertion to ensure that this generated file
//// is compatible with the grpc package it is being compiled against.
//const _ = grpc.SupportPackageIsVersion6
//
//// UserServiceClient is the client API for UserService service.
////
//// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
//type UserServiceClient interface {
//	Register(ctx context.Context, in *REGISTER, opts ...grpc.CallOption) (*USER, error)
//	SignIn(ctx context.Context, in *LOGIN, opts ...grpc.CallOption) (*VALID, error)
//	GetUsers(ctx context.Context, in *REQ, opts ...grpc.CallOption) (*USERS, error)
//	CheckUserNameExists(ctx context.Context, in *USERNAME, opts ...grpc.CallOption) (*VALID, error)
//	GenerateAccessToken(ctx context.Context, in *USERNAME, opts ...grpc.CallOption) (*TOKEN, error)
//	CheckAccessTokenValid(ctx context.Context, in *CHECKACCESSTOKEN, opts ...grpc.CallOption) (*VALID, error)
//}
//
//type userServiceClient struct {
//	cc grpc.ClientConnInterface
//}
//
//func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
//	return &userServiceClient{cc}
//}
//
//func (c *userServiceClient) Register(ctx context.Context, in *REGISTER, opts ...grpc.CallOption) (*USER, error) {
//	out := new(USER)
//	err := c.cc.Invoke(ctx, "/userproto.UserService/Register", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userServiceClient) SignIn(ctx context.Context, in *LOGIN, opts ...grpc.CallOption) (*VALID, error) {
//	out := new(VALID)
//	err := c.cc.Invoke(ctx, "/userproto.UserService/SignIn", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userServiceClient) GetUsers(ctx context.Context, in *REQ, opts ...grpc.CallOption) (*USERS, error) {
//	out := new(USERS)
//	err := c.cc.Invoke(ctx, "/userproto.UserService/GetUsers", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userServiceClient) CheckUserNameExists(ctx context.Context, in *USERNAME, opts ...grpc.CallOption) (*VALID, error) {
//	out := new(VALID)
//	err := c.cc.Invoke(ctx, "/userproto.UserService/CheckUserNameExists", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userServiceClient) GenerateAccessToken(ctx context.Context, in *USERNAME, opts ...grpc.CallOption) (*TOKEN, error) {
//	out := new(TOKEN)
//	err := c.cc.Invoke(ctx, "/userproto.UserService/GenerateAccessToken", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userServiceClient) CheckAccessTokenValid(ctx context.Context, in *CHECKACCESSTOKEN, opts ...grpc.CallOption) (*VALID, error) {
//	out := new(VALID)
//	err := c.cc.Invoke(ctx, "/userproto.UserService/CheckAccessTokenValid", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//// UserServiceServer is the server API for UserService service.
//type UserServiceServer interface {
//	Register(context.Context, *REGISTER) (*USER, error)
//	SignIn(context.Context, *LOGIN) (*VALID, error)
//	GetUsers(context.Context, *REQ) (*USERS, error)
//	CheckUserNameExists(context.Context, *USERNAME) (*VALID, error)
//	GenerateAccessToken(context.Context, *USERNAME) (*TOKEN, error)
//	CheckAccessTokenValid(context.Context, *CHECKACCESSTOKEN) (*VALID, error)
//}
//
//// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
//type UnimplementedUserServiceServer struct {
//}
//
//func (*UnimplementedUserServiceServer) Register(context.Context, *REGISTER) (*USER, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
//}
//func (*UnimplementedUserServiceServer) SignIn(context.Context, *LOGIN) (*VALID, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
//}
//func (*UnimplementedUserServiceServer) GetUsers(context.Context, *REQ) (*USERS, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
//}
//func (*UnimplementedUserServiceServer) CheckUserNameExists(context.Context, *USERNAME) (*VALID, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method CheckUserNameExists not implemented")
//}
//func (*UnimplementedUserServiceServer) GenerateAccessToken(context.Context, *USERNAME) (*TOKEN, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessToken not implemented")
//}
//func (*UnimplementedUserServiceServer) CheckAccessTokenValid(context.Context, *CHECKACCESSTOKEN) (*VALID, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method CheckAccessTokenValid not implemented")
//}
//
//func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
//	s.RegisterService(&_UserService_serviceDesc, srv)
//}
//
//func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(REGISTER)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServiceServer).Register(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/userproto.UserService/Register",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServiceServer).Register(ctx, req.(*REGISTER))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _UserService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(LOGIN)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServiceServer).SignIn(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/userproto.UserService/SignIn",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServiceServer).SignIn(ctx, req.(*LOGIN))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(REQ)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServiceServer).GetUsers(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/userproto.UserService/GetUsers",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServiceServer).GetUsers(ctx, req.(*REQ))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _UserService_CheckUserNameExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(USERNAME)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServiceServer).CheckUserNameExists(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/userproto.UserService/CheckUserNameExists",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServiceServer).CheckUserNameExists(ctx, req.(*USERNAME))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _UserService_GenerateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(USERNAME)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServiceServer).GenerateAccessToken(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/userproto.UserService/GenerateAccessToken",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServiceServer).GenerateAccessToken(ctx, req.(*USERNAME))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _UserService_CheckAccessTokenValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(CHECKACCESSTOKEN)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServiceServer).CheckAccessTokenValid(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/userproto.UserService/CheckAccessTokenValid",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServiceServer).CheckAccessTokenValid(ctx, req.(*CHECKACCESSTOKEN))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//var _UserService_serviceDesc = grpc.ServiceDesc{
//	ServiceName: "userproto.UserService",
//	HandlerType: (*UserServiceServer)(nil),
//	Methods: []grpc.MethodDesc{
//		{
//			MethodName: "Register",
//			Handler:    _UserService_Register_Handler,
//		},
//		{
//			MethodName: "SignIn",
//			Handler:    _UserService_SignIn_Handler,
//		},
//		{
//			MethodName: "GetUsers",
//			Handler:    _UserService_GetUsers_Handler,
//		},
//		{
//			MethodName: "CheckUserNameExists",
//			Handler:    _UserService_CheckUserNameExists_Handler,
//		},
//		{
//			MethodName: "GenerateAccessToken",
//			Handler:    _UserService_GenerateAccessToken_Handler,
//		},
//		{
//			MethodName: "CheckAccessTokenValid",
//			Handler:    _UserService_CheckAccessTokenValid_Handler,
//		},
//	},
//	Streams:  []grpc.StreamDesc{},
//	Metadata: "common/proto/users.proto",
//}
