// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dsl.proto

package dsl

import (
	context "context"
	models "ds-project/common/proto/models"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddPostRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Post                 string   `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostRequest) Reset()         { *m = AddPostRequest{} }
func (m *AddPostRequest) String() string { return proto.CompactTextString(m) }
func (*AddPostRequest) ProtoMessage()    {}
func (*AddPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{0}
}

func (m *AddPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostRequest.Unmarshal(m, b)
}
func (m *AddPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostRequest.Marshal(b, m, deterministic)
}
func (m *AddPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostRequest.Merge(m, src)
}
func (m *AddPostRequest) XXX_Size() int {
	return xxx_messageInfo_AddPostRequest.Size(m)
}
func (m *AddPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostRequest proto.InternalMessageInfo

func (m *AddPostRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddPostRequest) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

type AddPostResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostResponse) Reset()         { *m = AddPostResponse{} }
func (m *AddPostResponse) String() string { return proto.CompactTextString(m) }
func (*AddPostResponse) ProtoMessage()    {}
func (*AddPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{1}
}

func (m *AddPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostResponse.Unmarshal(m, b)
}
func (m *AddPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostResponse.Marshal(b, m, deterministic)
}
func (m *AddPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostResponse.Merge(m, src)
}
func (m *AddPostResponse) XXX_Size() int {
	return xxx_messageInfo_AddPostResponse.Size(m)
}
func (m *AddPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostResponse proto.InternalMessageInfo

func (m *AddPostResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetPostsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsRequest) Reset()         { *m = GetPostsRequest{} }
func (m *GetPostsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostsRequest) ProtoMessage()    {}
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{2}
}

func (m *GetPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsRequest.Unmarshal(m, b)
}
func (m *GetPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsRequest.Marshal(b, m, deterministic)
}
func (m *GetPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsRequest.Merge(m, src)
}
func (m *GetPostsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostsRequest.Size(m)
}
func (m *GetPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsRequest proto.InternalMessageInfo

func (m *GetPostsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetPostsResponse struct {
	Posts                []*models.Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPostsResponse) Reset()         { *m = GetPostsResponse{} }
func (m *GetPostsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostsResponse) ProtoMessage()    {}
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{3}
}

func (m *GetPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsResponse.Unmarshal(m, b)
}
func (m *GetPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsResponse.Marshal(b, m, deterministic)
}
func (m *GetPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsResponse.Merge(m, src)
}
func (m *GetPostsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostsResponse.Size(m)
}
func (m *GetPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsResponse proto.InternalMessageInfo

func (m *GetPostsResponse) GetPosts() []*models.Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type GetSubscriptionsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionsRequest) Reset()         { *m = GetSubscriptionsRequest{} }
func (m *GetSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionsRequest) ProtoMessage()    {}
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{4}
}

func (m *GetSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionsRequest.Unmarshal(m, b)
}
func (m *GetSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionsRequest.Merge(m, src)
}
func (m *GetSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionsRequest.Size(m)
}
func (m *GetSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionsRequest proto.InternalMessageInfo

func (m *GetSubscriptionsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetSubscriptionsResponse struct {
	Subscriptions        []string `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionsResponse) Reset()         { *m = GetSubscriptionsResponse{} }
func (m *GetSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionsResponse) ProtoMessage()    {}
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{5}
}

func (m *GetSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionsResponse.Unmarshal(m, b)
}
func (m *GetSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionsResponse.Merge(m, src)
}
func (m *GetSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionsResponse.Size(m)
}
func (m *GetSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionsResponse proto.InternalMessageInfo

func (m *GetSubscriptionsResponse) GetSubscriptions() []string {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type SubscribeRequest struct {
	Subscriber           string   `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	Publisher            string   `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{6}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetSubscriber() string {
	if m != nil {
		return m.Subscriber
	}
	return ""
}

func (m *SubscribeRequest) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

type SubscribeResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{7}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

func (m *SubscribeResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SetAccessTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAccessTokenRequest) Reset()         { *m = SetAccessTokenRequest{} }
func (m *SetAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*SetAccessTokenRequest) ProtoMessage()    {}
func (*SetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{8}
}

func (m *SetAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAccessTokenRequest.Unmarshal(m, b)
}
func (m *SetAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *SetAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAccessTokenRequest.Merge(m, src)
}
func (m *SetAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_SetAccessTokenRequest.Size(m)
}
func (m *SetAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAccessTokenRequest proto.InternalMessageInfo

func (m *SetAccessTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SetAccessTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AccessTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenRequest) Reset()         { *m = AccessTokenRequest{} }
func (m *AccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AccessTokenRequest) ProtoMessage()    {}
func (*AccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{9}
}

func (m *AccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenRequest.Unmarshal(m, b)
}
func (m *AccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *AccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenRequest.Merge(m, src)
}
func (m *AccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AccessTokenRequest.Size(m)
}
func (m *AccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenRequest proto.InternalMessageInfo

func (m *AccessTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetAccessTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenResponse) Reset()         { *m = GetAccessTokenResponse{} }
func (m *GetAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenResponse) ProtoMessage()    {}
func (*GetAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{10}
}

func (m *GetAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenResponse.Unmarshal(m, b)
}
func (m *GetAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenResponse.Merge(m, src)
}
func (m *GetAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenResponse.Size(m)
}
func (m *GetAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenResponse proto.InternalMessageInfo

func (m *GetAccessTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetAccessTokenResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UpdateAccessTokenResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccessTokenResponse) Reset()         { *m = UpdateAccessTokenResponse{} }
func (m *UpdateAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccessTokenResponse) ProtoMessage()    {}
func (*UpdateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{11}
}

func (m *UpdateAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccessTokenResponse.Unmarshal(m, b)
}
func (m *UpdateAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccessTokenResponse.Merge(m, src)
}
func (m *UpdateAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccessTokenResponse.Size(m)
}
func (m *UpdateAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccessTokenResponse proto.InternalMessageInfo

func (m *UpdateAccessTokenResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

// Messages for users
type GetUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{12}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserResponse struct {
	User                 *models.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Ok                   bool         `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{13}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *models.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{14}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

type GetUsersResponse struct {
	Users                map[string]*models.User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{15}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() map[string]*models.User {
	if m != nil {
		return m.Users
	}
	return nil
}

type CreateUserRequest struct {
	Username             string       `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	User                 *models.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{16}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetUser() *models.User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{17}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*AddPostRequest)(nil), "dsl.AddPostRequest")
	proto.RegisterType((*AddPostResponse)(nil), "dsl.AddPostResponse")
	proto.RegisterType((*GetPostsRequest)(nil), "dsl.GetPostsRequest")
	proto.RegisterType((*GetPostsResponse)(nil), "dsl.GetPostsResponse")
	proto.RegisterType((*GetSubscriptionsRequest)(nil), "dsl.GetSubscriptionsRequest")
	proto.RegisterType((*GetSubscriptionsResponse)(nil), "dsl.GetSubscriptionsResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "dsl.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "dsl.SubscribeResponse")
	proto.RegisterType((*SetAccessTokenRequest)(nil), "dsl.SetAccessTokenRequest")
	proto.RegisterType((*AccessTokenRequest)(nil), "dsl.AccessTokenRequest")
	proto.RegisterType((*GetAccessTokenResponse)(nil), "dsl.GetAccessTokenResponse")
	proto.RegisterType((*UpdateAccessTokenResponse)(nil), "dsl.UpdateAccessTokenResponse")
	proto.RegisterType((*GetUserRequest)(nil), "dsl.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "dsl.GetUserResponse")
	proto.RegisterType((*GetUsersRequest)(nil), "dsl.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "dsl.GetUsersResponse")
	proto.RegisterMapType((map[string]*models.User)(nil), "dsl.GetUsersResponse.UsersEntry")
	proto.RegisterType((*CreateUserRequest)(nil), "dsl.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "dsl.CreateUserResponse")
}

func init() {
	proto.RegisterFile("dsl.proto", fileDescriptor_3e64ff22355f731d)
}

var fileDescriptor_3e64ff22355f731d = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x86, 0x36, 0x93, 0x92, 0x26, 0x4b, 0xda, 0x04, 0xf7, 0x43, 0x61, 0xe9, 0xa1,
	0x12, 0x34, 0x41, 0xa5, 0x14, 0x54, 0x01, 0x6a, 0x69, 0x69, 0x84, 0x54, 0x89, 0x92, 0x90, 0x0b,
	0x37, 0xc7, 0x1e, 0x89, 0x10, 0xc7, 0x6b, 0xbc, 0x9b, 0x4a, 0xfd, 0x1b, 0xfc, 0x3b, 0xfe, 0x0d,
	0xf2, 0xee, 0xda, 0xb1, 0x9d, 0x44, 0x04, 0x6e, 0xce, 0x9b, 0x99, 0xf7, 0x66, 0x67, 0xe7, 0x6d,
	0xa0, 0xe8, 0x72, 0xaf, 0x15, 0x84, 0x4c, 0x30, 0xb2, 0xe2, 0x72, 0xcf, 0xda, 0x18, 0x33, 0x17,
	0x3d, 0xae, 0x20, 0x7a, 0x0e, 0xe5, 0x0b, 0xd7, 0xbd, 0x65, 0x5c, 0x74, 0xf1, 0xe7, 0x04, 0xb9,
	0x20, 0x16, 0xac, 0x4f, 0x38, 0x86, 0xbe, 0x3d, 0xc6, 0x86, 0xd1, 0x34, 0x0e, 0x8b, 0xdd, 0xe4,
	0x37, 0x21, 0xb0, 0x1a, 0x30, 0x2e, 0x1a, 0xa6, 0xc4, 0xe5, 0x37, 0x7d, 0x02, 0x9b, 0x09, 0x03,
	0x0f, 0x98, 0xcf, 0x91, 0x94, 0xc1, 0x64, 0x23, 0x59, 0xbc, 0xde, 0x35, 0xd9, 0x88, 0x1e, 0xc1,
	0x66, 0x07, 0x45, 0x94, 0xc2, 0x97, 0x50, 0xa1, 0xa7, 0x50, 0x99, 0xa6, 0x6b, 0x4a, 0x0a, 0x85,
	0x48, 0x8d, 0x37, 0x8c, 0xe6, 0xca, 0x61, 0xe9, 0x78, 0xa3, 0xa5, 0x4f, 0x21, 0x75, 0x55, 0x88,
	0xbe, 0x82, 0x7a, 0x07, 0x45, 0x6f, 0x32, 0xe0, 0x4e, 0x38, 0x0c, 0xc4, 0x90, 0xf9, 0x4b, 0xc9,
	0x9d, 0x43, 0x63, 0xb6, 0x4c, 0xcb, 0x1e, 0xc0, 0x43, 0x9e, 0x0e, 0x48, 0xf9, 0x62, 0x37, 0x0b,
	0xd2, 0x5b, 0xa8, 0xe8, 0xf2, 0x01, 0xc6, 0x8a, 0xfb, 0x00, 0x3c, 0xc6, 0x42, 0xad, 0x99, 0x42,
	0xc8, 0x2e, 0x14, 0x83, 0xc9, 0xc0, 0x1b, 0xf2, 0xef, 0x18, 0xea, 0x79, 0x4e, 0x01, 0xfa, 0x14,
	0xaa, 0x29, 0xc6, 0x05, 0x63, 0xfd, 0x04, 0x5b, 0x3d, 0x14, 0x17, 0x8e, 0x83, 0x9c, 0x7f, 0x65,
	0x23, 0xf4, 0x97, 0xb9, 0xc2, 0x1a, 0x14, 0x44, 0x94, 0xab, 0x35, 0xd5, 0x0f, 0xfa, 0x02, 0xc8,
	0xbf, 0xf1, 0xd0, 0xf7, 0xb0, 0xdd, 0xc9, 0x89, 0xeb, 0x36, 0x13, 0x05, 0x23, 0xa5, 0xa0, 0x9b,
	0x37, 0x93, 0xe6, 0x9f, 0xc1, 0xe3, 0x7e, 0xe0, 0xda, 0x02, 0xe7, 0x51, 0xe4, 0x4f, 0xfa, 0x1c,
	0xca, 0x1d, 0x14, 0x7d, 0x8e, 0xe1, 0x32, 0xad, 0x5d, 0xca, 0x75, 0x53, 0xd9, 0x9a, 0xb0, 0x09,
	0xab, 0x51, 0x58, 0xa6, 0xa6, 0xb6, 0x47, 0xe6, 0xc8, 0xc8, 0x4c, 0x7f, 0xd5, 0x84, 0x24, 0x5e,
	0x22, 0xfa, 0xcb, 0x90, 0x8b, 0xa9, 0x31, 0xcd, 0x7c, 0x0a, 0x85, 0xa8, 0x3e, 0x5e, 0xcc, 0x66,
	0x2b, 0xb2, 0x5b, 0x3e, 0x4b, 0x0a, 0xf1, 0x8f, 0xbe, 0x08, 0xef, 0xbb, 0x2a, 0xdd, 0xba, 0x06,
	0x98, 0x82, 0xa4, 0x02, 0x2b, 0x23, 0xbc, 0xd7, 0x27, 0x89, 0x3e, 0xa3, 0x85, 0xbf, 0xb3, 0xbd,
	0x09, 0xca, 0x96, 0xf2, 0x2d, 0xab, 0xd0, 0x99, 0xf9, 0xc6, 0xa0, 0x5f, 0xa0, 0x7a, 0x19, 0xa2,
	0x2d, 0x70, 0xc9, 0xe9, 0x24, 0xa3, 0x30, 0x17, 0x8d, 0x82, 0x1e, 0x00, 0x49, 0x53, 0xce, 0xbf,
	0x93, 0xe3, 0xdf, 0x05, 0x28, 0x5d, 0xd9, 0xc2, 0xee, 0x61, 0x78, 0x37, 0x74, 0x90, 0x9c, 0xc0,
	0x9a, 0x7e, 0x07, 0xc8, 0x23, 0x39, 0x84, 0xec, 0xbb, 0x62, 0xd5, 0xb2, 0xa0, 0x66, 0x7d, 0x0d,
	0xeb, 0xb1, 0xd7, 0x49, 0x2d, 0x9e, 0x5d, 0xfa, 0xa5, 0xb0, 0xb6, 0x72, 0xa8, 0x2e, 0xfc, 0x2c,
	0xef, 0x22, 0xe3, 0x5a, 0xb2, 0x1b, 0xa7, 0xce, 0x7b, 0x03, 0xac, 0xbd, 0x05, 0x51, 0x4d, 0x78,
	0x06, 0xc5, 0xc4, 0x72, 0x44, 0x89, 0xe6, 0x4d, 0x6d, 0x6d, 0xe7, 0x61, 0x5d, 0xfb, 0x16, 0x4a,
	0x7d, 0x9f, 0xff, 0x6f, 0xf5, 0x0d, 0x94, 0xb3, 0x3e, 0x26, 0x96, 0xca, 0x9c, 0x67, 0x6e, 0x6b,
	0x5f, 0xc6, 0x16, 0x7b, 0xe7, 0x5a, 0x7a, 0x25, 0xcd, 0x56, 0x57, 0x93, 0x9f, 0xa5, 0xda, 0x89,
	0x27, 0x32, 0x8f, 0xe7, 0x06, 0xaa, 0x57, 0xe8, 0x61, 0x46, 0x64, 0x31, 0xd5, 0xdf, 0xba, 0x3a,
	0x81, 0x35, 0x6d, 0x0a, 0xbd, 0x1d, 0x59, 0x3f, 0x5b, 0xb5, 0x2c, 0x98, 0xd9, 0x0e, 0xe9, 0x13,
	0x52, 0xcb, 0x39, 0x2b, 0xb7, 0x1d, 0x59, 0x57, 0xbe, 0x03, 0x98, 0xae, 0x30, 0x51, 0x83, 0x9f,
	0xb1, 0x89, 0x55, 0x9f, 0xc1, 0x55, 0xf9, 0x87, 0xbd, 0x6f, 0x3b, 0x2e, 0x3f, 0x0a, 0x42, 0xf6,
	0x03, 0x1d, 0xd1, 0x76, 0xd8, 0x78, 0xcc, 0xfc, 0xb6, 0xfc, 0xc3, 0x6c, 0xbb, 0xdc, 0x1b, 0x3c,
	0x90, 0x9f, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x08, 0xec, 0x64, 0x3b, 0x5b, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	// Services related to posts
	AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error)
	GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
	// Services related to subscriptions
	GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*GetSubscriptionsResponse, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	Unsubscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	// Services related to auth
	SetAccessToken(ctx context.Context, in *SetAccessTokenRequest, opts ...grpc.CallOption) (*UpdateAccessTokenResponse, error)
	GetAccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error)
	DeleteAccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*UpdateAccessTokenResponse, error)
	// Services related to users
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error) {
	out := new(AddPostResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/AddPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*GetSubscriptionsResponse, error) {
	out := new(GetSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/GetSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) Unsubscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) SetAccessToken(ctx context.Context, in *SetAccessTokenRequest, opts ...grpc.CallOption) (*UpdateAccessTokenResponse, error) {
	out := new(UpdateAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/SetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetAccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error) {
	out := new(GetAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) DeleteAccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*UpdateAccessTokenResponse, error) {
	out := new(UpdateAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/DeleteAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/dsl.DataService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	// Services related to posts
	AddPost(context.Context, *AddPostRequest) (*AddPostResponse, error)
	GetPosts(context.Context, *GetPostsRequest) (*GetPostsResponse, error)
	// Services related to subscriptions
	GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*GetSubscriptionsResponse, error)
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	Unsubscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	// Services related to auth
	SetAccessToken(context.Context, *SetAccessTokenRequest) (*UpdateAccessTokenResponse, error)
	GetAccessToken(context.Context, *AccessTokenRequest) (*GetAccessTokenResponse, error)
	DeleteAccessToken(context.Context, *AccessTokenRequest) (*UpdateAccessTokenResponse, error)
	// Services related to users
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) AddPost(ctx context.Context, req *AddPostRequest) (*AddPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPost not implemented")
}
func (*UnimplementedDataServiceServer) GetPosts(ctx context.Context, req *GetPostsRequest) (*GetPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}
func (*UnimplementedDataServiceServer) GetSubscriptions(ctx context.Context, req *GetSubscriptionsRequest) (*GetSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (*UnimplementedDataServiceServer) Subscribe(ctx context.Context, req *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedDataServiceServer) Unsubscribe(ctx context.Context, req *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (*UnimplementedDataServiceServer) SetAccessToken(ctx context.Context, req *SetAccessTokenRequest) (*UpdateAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAccessToken not implemented")
}
func (*UnimplementedDataServiceServer) GetAccessToken(ctx context.Context, req *AccessTokenRequest) (*GetAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessToken not implemented")
}
func (*UnimplementedDataServiceServer) DeleteAccessToken(ctx context.Context, req *AccessTokenRequest) (*UpdateAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccessToken not implemented")
}
func (*UnimplementedDataServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedDataServiceServer) GetUsers(ctx context.Context, req *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedDataServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/AddPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).AddPost(ctx, req.(*AddPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetPosts(ctx, req.(*GetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/GetSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetSubscriptions(ctx, req.(*GetSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Unsubscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_SetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).SetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/SetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).SetAccessToken(ctx, req.(*SetAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetAccessToken(ctx, req.(*AccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_DeleteAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).DeleteAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/DeleteAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).DeleteAccessToken(ctx, req.(*AccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsl.DataService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dsl.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPost",
			Handler:    _DataService_AddPost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _DataService_GetPosts_Handler,
		},
		{
			MethodName: "GetSubscriptions",
			Handler:    _DataService_GetSubscriptions_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _DataService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _DataService_Unsubscribe_Handler,
		},
		{
			MethodName: "SetAccessToken",
			Handler:    _DataService_SetAccessToken_Handler,
		},
		{
			MethodName: "GetAccessToken",
			Handler:    _DataService_GetAccessToken_Handler,
		},
		{
			MethodName: "DeleteAccessToken",
			Handler:    _DataService_DeleteAccessToken_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _DataService_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _DataService_GetUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _DataService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsl.proto",
}
