// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts.proto

package posts

import (
	context "context"
	models "ds-project/common/proto/models"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddPostRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Post                 string   `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostRequest) Reset()         { *m = AddPostRequest{} }
func (m *AddPostRequest) String() string { return proto.CompactTextString(m) }
func (*AddPostRequest) ProtoMessage()    {}
func (*AddPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{0}
}

func (m *AddPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostRequest.Unmarshal(m, b)
}
func (m *AddPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostRequest.Marshal(b, m, deterministic)
}
func (m *AddPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostRequest.Merge(m, src)
}
func (m *AddPostRequest) XXX_Size() int {
	return xxx_messageInfo_AddPostRequest.Size(m)
}
func (m *AddPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostRequest proto.InternalMessageInfo

func (m *AddPostRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddPostRequest) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

type AddPostResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostResponse) Reset()         { *m = AddPostResponse{} }
func (m *AddPostResponse) String() string { return proto.CompactTextString(m) }
func (*AddPostResponse) ProtoMessage()    {}
func (*AddPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{1}
}

func (m *AddPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostResponse.Unmarshal(m, b)
}
func (m *AddPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostResponse.Marshal(b, m, deterministic)
}
func (m *AddPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostResponse.Merge(m, src)
}
func (m *AddPostResponse) XXX_Size() int {
	return xxx_messageInfo_AddPostResponse.Size(m)
}
func (m *AddPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostResponse proto.InternalMessageInfo

func (m *AddPostResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetPostsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsRequest) Reset()         { *m = GetPostsRequest{} }
func (m *GetPostsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostsRequest) ProtoMessage()    {}
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{2}
}

func (m *GetPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsRequest.Unmarshal(m, b)
}
func (m *GetPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsRequest.Marshal(b, m, deterministic)
}
func (m *GetPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsRequest.Merge(m, src)
}
func (m *GetPostsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostsRequest.Size(m)
}
func (m *GetPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsRequest proto.InternalMessageInfo

func (m *GetPostsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetPostsResponse struct {
	Posts                []*models.Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPostsResponse) Reset()         { *m = GetPostsResponse{} }
func (m *GetPostsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostsResponse) ProtoMessage()    {}
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{3}
}

func (m *GetPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsResponse.Unmarshal(m, b)
}
func (m *GetPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsResponse.Marshal(b, m, deterministic)
}
func (m *GetPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsResponse.Merge(m, src)
}
func (m *GetPostsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostsResponse.Size(m)
}
func (m *GetPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsResponse proto.InternalMessageInfo

func (m *GetPostsResponse) GetPosts() []*models.Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*AddPostRequest)(nil), "posts.AddPostRequest")
	proto.RegisterType((*AddPostResponse)(nil), "posts.AddPostResponse")
	proto.RegisterType((*GetPostsRequest)(nil), "posts.GetPostsRequest")
	proto.RegisterType((*GetPostsResponse)(nil), "posts.GetPostsResponse")
}

func init() {
	proto.RegisterFile("posts.proto", fileDescriptor_b14bd1586479c33d)
}

var fileDescriptor_b14bd1586479c33d = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0xf1, 0xa7, 0x71, 0x1a, 0x5a, 0x19, 0x50, 0x43, 0x40, 0xac, 0x7b, 0xea, 0xa5, 0x09,
	0x54, 0x10, 0xd1, 0x8b, 0x7a, 0xb0, 0x57, 0x89, 0x37, 0x6f, 0x9a, 0x9d, 0x83, 0xd6, 0x64, 0x62,
	0x66, 0xeb, 0xfb, 0xf9, 0x66, 0xd2, 0xc9, 0xb6, 0x62, 0xbd, 0xe8, 0x6d, 0xe7, 0xdb, 0xf9, 0xfe,
	0x76, 0xa1, 0xdf, 0xb0, 0x38, 0xc9, 0x9a, 0x96, 0x1d, 0xe3, 0x8e, 0x0e, 0x69, 0x5c, 0xb1, 0xa5,
	0x37, 0x0f, 0x9a, 0x6b, 0x18, 0xdc, 0x58, 0x7b, 0xcf, 0xe2, 0x0a, 0x7a, 0x5f, 0x90, 0x38, 0x4c,
	0x21, 0x5a, 0x08, 0xb5, 0xf5, 0x53, 0x45, 0x49, 0x30, 0x0a, 0xc6, 0x7b, 0xc5, 0x7a, 0x46, 0x84,
	0xed, 0xa5, 0x48, 0x12, 0x2a, 0xae, 0x67, 0x73, 0x0a, 0xc3, 0xb5, 0x82, 0x34, 0x5c, 0x0b, 0xe1,
	0x00, 0x42, 0x9e, 0x2b, 0x39, 0x2a, 0x42, 0x9e, 0x9b, 0x09, 0x0c, 0x67, 0xe4, 0x96, 0x2b, 0xf2,
	0x07, 0x17, 0x73, 0x0e, 0xfb, 0xdf, 0xeb, 0x5e, 0xd2, 0x40, 0x17, 0x3f, 0x09, 0x46, 0x5b, 0xe3,
	0xfe, 0x34, 0xce, 0x7c, 0x0b, 0xf5, 0xed, 0xae, 0xa6, 0x9f, 0x01, 0xc4, 0xca, 0x7a, 0xa0, 0xf6,
	0xe3, 0xa5, 0x24, 0xbc, 0x80, 0x9e, 0x8f, 0x86, 0x07, 0x59, 0xf7, 0x14, 0x3f, 0xcb, 0xa6, 0x87,
	0x9b, 0xb0, 0xb7, 0xbb, 0x82, 0x68, 0x15, 0x01, 0x57, 0x3b, 0x1b, 0x15, 0xd2, 0xa3, 0x5f, 0xb8,
	0x27, 0x5f, 0x42, 0x6f, 0x46, 0xee, 0x8e, 0xc8, 0xfe, 0x9b, 0x7b, 0x7b, 0xf2, 0x78, 0x6c, 0x65,
	0xd2, 0xb4, 0xfc, 0x4a, 0xa5, 0xcb, 0x4b, 0xae, 0x2a, 0xae, 0x73, 0xfd, 0xaa, 0x5c, 0x19, 0xcf,
	0xbb, 0x3a, 0x9c, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xa9, 0x06, 0xcd, 0xdb, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsServiceClient interface {
	AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error)
	GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
	GetFeed(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
}

type postsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsServiceClient(cc grpc.ClientConnInterface) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error) {
	out := new(AddPostResponse)
	err := c.cc.Invoke(ctx, "/posts.PostsService/AddPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, "/posts.PostsService/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetFeed(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, "/posts.PostsService/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
type PostsServiceServer interface {
	AddPost(context.Context, *AddPostRequest) (*AddPostResponse, error)
	GetPosts(context.Context, *GetPostsRequest) (*GetPostsResponse, error)
	GetFeed(context.Context, *GetPostsRequest) (*GetPostsResponse, error)
}

// UnimplementedPostsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostsServiceServer struct {
}

func (*UnimplementedPostsServiceServer) AddPost(ctx context.Context, req *AddPostRequest) (*AddPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPost not implemented")
}
func (*UnimplementedPostsServiceServer) GetPosts(ctx context.Context, req *GetPostsRequest) (*GetPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}
func (*UnimplementedPostsServiceServer) GetFeed(ctx context.Context, req *GetPostsRequest) (*GetPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}

func RegisterPostsServiceServer(s *grpc.Server, srv PostsServiceServer) {
	s.RegisterService(&_PostsService_serviceDesc, srv)
}

func _PostsService_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/posts.PostsService/AddPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).AddPost(ctx, req.(*AddPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/posts.PostsService/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPosts(ctx, req.(*GetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/posts.PostsService/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetFeed(ctx, req.(*GetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "posts.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPost",
			Handler:    _PostsService_AddPost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _PostsService_GetPosts_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _PostsService_GetFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts.proto",
}
